#!/usr/bin/bash
set -euo pipefail

red=$(tput setaf 1)
green=$(tput setaf 2)
yellow=$(tput setaf 3)
purple=$(tput setaf 5)
bold=$(tput bold)
reset=$(tput sgr0)

_w() {
    local -r text="${1:-}"
    echo -e "$text"
}

_abort() { _error "$1"; _w ; exit 1; }

_info()    { _w " ${bold}${green}>${reset} $1"; }
_success() { _w " ${green}✔ $1${reset}"; }
_warning() { _w " ${yellow}${bold}!${reset}${yellow} $1${reset}"; }
_error()   { _w " ${red}✖ $1${reset}"; }
_quest()   { read -rp "${bold}$1${reset} " "$2"; }

_w
read -rp "Where do you want to clone $(tput setaf 6)rixsilverith/cse-notes$(tput sgr0)?" "LECTURE_NOTES_HOME"
_w

export LECTURE_NOTES_HOME="${LECTURE_NOTES_HOME:-$HOME/cse-notes}"

_info "Cloning into $(tput setaf 6)$LECTURE_NOTES_HOME$(tput sgr0)"
git clone https://github.com/rixsilverith/cse-notes.git "$LECTURE_NOTES_HOME" >/dev/null 2>&1
